### ISSUE TITLE
Reg: Perfjankie usage

### ISSUE THREAD

**Issue by settysreekanth** [axemclion/perfjankie#15]
Hi @axemclion could you please help me in setting up perfjankie .. I am able to run browser-perf and get the metrics but I am not able to understand perfjankie usage and how to start with? I have angular appplication running in my local and I am interested to see the performance metrics in graphical format.

**Comment by axemclion** [comment]
Setting up perfjankie should be easy. You would need a CouchDB server (or user something like iriscouch.com or cloudant.com). You can use perfjankie either as a node module or from the command line - both are documented in the README file. 

Are there specific questions you have?

**Comment by settysreekanth** [comment]
@axemclion could you please explain more details about cli command..

$ perfjankie --config-file=local.config.json --only-update-site

1.which config file is this?
2.Only update site meaning?

My apologies if I am asking basic question.. as I am new to this performance measurement.

**Comment by axemclion** [comment]
The config file could look something like this - https://github.com/axemclion/perfjankie/blob/master/test/res/local.config.json

update-site basically means that the UI code is uploaded to the database. Perfjankie uses couchDB and uploads all the UI to view the graphs (like this - http://nparashuram.com/perfslides/perfjankie) to CouchDB. 
You need to update the site only once - you can then start running tests, and only the data will be uploaded. 

These questions are great - I did try to cover them in README.md,  but if you think some of these things are not clear, please do send in a pull request so that people looking at the project in the future can understand it better.
