### ISSUE TITLE
Parse HTML data missing

### ISSUE THREAD

**Issue by arschmitz** [axemclion/perfjankie#22]
Getting "Could not plot graph due to error in data" no errors or issues while running

**Comment by axemclion** [comment]
Browser-perf earlier used to generate a ParseHTML event for most pages. I then discovered that this was not due to the page itself, but was actually due to opening about:tracing. To remove this issue, I now pick up about:tracing information from chromedriver. This is why you dont see parseHTML. 

Are there parseHTML events on the page that you observe on the timeline ? Can you share the page so that I can see it ?

If you still would like to know parseHTML, you may want to "load" a page, instead of just "scrolling" a page that is already loaded; the latter being the default action now.

**Comment by axemclion** [comment]
Closing this issue as it has been inactive for a while, and there is no action on this. `browser-perf`, the underlying system that collects data has improved to give us much more data, so this should be solved.

If you think that this problem still exists, please reopen the issue.
